# Generated by Django 3.0.8 on 2020-08-01 11:55

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200726_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumb',
            field=sorl.thumbnail.fields.ImageField(default='thumb', upload_to='projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=sorl.thumbnail.fields.ImageField(default='icon', upload_to='services'),
            preserve_default=False,
        ),
    ]
